apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-cd-pipeline
spec:
  params:
    - name: repo-url
  tasks:
    - name: clone
      taskRef:
        name: checkout
      params:
        - name: repository-url
          value: "$(repo-url)"